version: '3'

services:
  app:
    image: python:3.9
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 127.0.0.1:5000:5000
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
    env_file:
      - .env
    command: bash -c "apt-get update && apt-get install -y libgl1-mesa-dev libglib2.0-0 libsm6 libxrender1 libxext6 ffmpeg && pip install -r requirements.txt && flask run"

